remove pow_to_mul pass that causes some issues in structural smoothing operators
```
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/dugwave-1402010+52.g3af59662505-py3.11-linux-x86_64.egg/dugwave/change_of_variables/structural_smoothing.p", line 188, in __init__
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/dugwave-1402010+52.g3af59662505-py3.11-linux-x86_64.egg/dugwave/change_of_variables/structural_smoothing.p", line 453, in make_smoothing_tensors_operator
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/dugwave-1402010+52.g3af59662505-py3.11-linux-x86_64.egg/dugwave/devitowrap.p", line 503, in make_operator
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/operator/operator.py", line 156, in __new__
    op = cls._build(expressions, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/operator/operator.py", line 174, in _build
    irs, byproduct = cls._lower(expressions, profiler=profiler, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/operator/operator.py", line 258, in _lower
    iet, byproduct = cls._lower_iet(uiet, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/timing.py", line 76, in __call__
    retval = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/operator/operator.py", line 431, in _lower_iet
    graph = cls._specialize_iet(graph, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/timing.py", line 76, in __call__
    retval = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/core/gpu.py", line 223, in _specialize_iet
    parizer.make_parallel(graph)
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/passes/iet/engine.py", line 125, in wrapper
    return maybe_timed(call(graph), func.__name__)(partial(func, self), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/timing.py", line 76, in __call__
    retval = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/passes/iet/engine.py", line 53, in apply
    efunc, metadata = func(self.efuncs[i], **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/passes/iet/parpragma.py", line 432, in make_parallel
    return self._make_parallel(iet)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/cudaizer.py", line 110, in _make_parallel
    root, partree, kernels_gen = self._extract_kernels(candidates)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/cudaizer.py", line 39, in _extract_kernels
    kernel, extracted_iterators = self._make_cuda_kernel(kernel_name, root)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/cudaizer.py", line 137, in _make_cuda_kernel
    body = realign_iet(body)
           ^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 86, in realign_iet
    return IterationLimitTranslator(ioffset_map).visit(iet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 111, in visit
    ret = self._visit(o, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 116, in visit_Iteration
    children = [self._visit(i, **kwargs) for i in o.children]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 116, in <listcomp>
    children = [self._visit(i, **kwargs) for i in o.children]
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in visit_tuple
    visited = tuple(self._visit(i, **kwargs) for i in o)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in <genexpr>
    visited = tuple(self._visit(i, **kwargs) for i in o)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 116, in visit_Iteration
    children = [self._visit(i, **kwargs) for i in o.children]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 116, in <listcomp>
    children = [self._visit(i, **kwargs) for i in o.children]
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in visit_tuple
    visited = tuple(self._visit(i, **kwargs) for i in o)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in <genexpr>
    visited = tuple(self._visit(i, **kwargs) for i in o)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 112, in visit_Iteration
    nodes=self._visit(o.nodes, **kwargs),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in visit_tuple
    visited = tuple(self._visit(i, **kwargs) for i in o)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in <genexpr>
    visited = tuple(self._visit(i, **kwargs) for i in o)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 136, in visit_Node
    children = [self._visit(i, **kwargs) for i in o.children]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 136, in <listcomp>
    children = [self._visit(i, **kwargs) for i in o.children]
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in visit_tuple
    visited = tuple(self._visit(i, **kwargs) for i in o)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 99, in <genexpr>
    visited = tuple(self._visit(i, **kwargs) for i in o)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/tools/visitors.py", line 118, in _visit
    return meth(o, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/cuda/passes/realign.py", line 130, in visit_Expression
    pow_to_mul(rhs),
    ^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/symbolics/manipulation.py", line 219, in pow_to_mul
    return expr.func(*[pow_to_mul(i) for i in expr.args], evaluate=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/symbolics/manipulation.py", line 219, in <listcomp>
    return expr.func(*[pow_to_mul(i) for i in expr.args], evaluate=False)
                       ^^^^^^^^^^^^^
  File "/data/pe1/dug/geodev/bamboo/dugwave-integration-tests-gpu/DUGLONGGPU4.1/env/lib/python3.11/site-packages/devito/symbolics/manipulation.py", line 219, in pow_to_mul
    return expr.func(*[pow_to_mul(i) for i in expr.args], evaluate=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ExprCondPair.__new__() got an unexpected keyword argument 'evaluate'
```